import { Metadata } from 'next';
import { ReactNode } from 'react';
import { Container } from '@/shared/components';
import { Header } from '@/widgets/header';

export const metadata: Metadata = {
  title: 'Da Da Pizza | Корзина',
  description: 'Generated by create next app',
};

export default function CheckoutLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Header
          hasCart={false}
          hasSearch={false}
          className={'border-gray-200'}
        />
        {children}
      </Container>
    </main>
  );
}
